syntax = "proto3";
option go_package = "./;proto";
package raft;

service Raft {
    rpc RequestVote (RequestVoteRequest) returns (RequestVoteResponse);
    rpc AppendEntries (AppendEntriesRequest) returns (AppendEntriesResponse);
}

message RequestVoteRequest {
    int32 term = 1;
    int32 candidate_id = 2;
}

message RequestVoteResponse {
    int32 term = 1;
    bool vote_granted = 2;
}

message Log{
    int32 term = 1;
    bytes data = 2;
}

message AppendEntriesRequest {
    int32 leaderId = 1;
    int32 term = 2;
    int32 prefixLen = 3;
    int32 prefixTerm = 4;
    int32 leaderCommit =5; 
    repeated int32 suffix = 6;
}

message AppendEntriesResponse {
    int32 term = 1;
    int32 ack = 2;
    bool success = 3;
}