syntax = "proto3";
option go_package = "./;proto";
package raft;

service Raft {
    rpc RequestVote (RequestVoteRequest) returns (RequestVoteResponse);
    rpc AppendEntries (AppendEntryRequest) returns (AppendEntryResponse);
}

message RequestVoteRequest {
    int32 term = 1;
    int32 candidate_id = 2;
}

message RequestVoteResponse {
    int32 term = 1;
    bool vote_granted = 2;
}

message AppendEntryRequest {
    int32 term = 1;
    repeated string entry = 2;
}

message AppendEntryResponse {

}